[package]
name = "pico-real-backend"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rrs_lib = { package = "rrs-succinct", version = "0.1.0" }
pico-vm = { path = "../../../beak-py/out/pico-22b0aae6321c1f63c72aafd0b506b5f45b91ffb1/pico-src/vm" }
